import React from 'react';
import { View, Text, ScrollView, TouchableOpacity, StyleSheet, Platform } from 'react-native';
import { useRouter } from 'expo-router';
import { StatusBar } from 'expo-status-bar';

const BG = '#09090B';
const BORDER = '#27272A';
const TEXT_PRIMARY = '#E4E4E7';
const TEXT_DIM = '#A1A1AA';
const MONO = Platform.select({ ios: 'Courier New', android: 'monospace', default: 'monospace' });

export default function TermsScreen() {
  const router = useRouter();

  return (
    <View style={styles.root}>
      <StatusBar style="light" />
      <View style={styles.inner}>
        <View style={styles.header}>
          <TouchableOpacity onPress={() => router.back()} hitSlop={{ top: 12, bottom: 12, left: 12, right: 12 }}>
            <Text style={styles.back}>← BACK</Text>
          </TouchableOpacity>
        </View>
        <View style={styles.divider} />

        <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
          <Text style={styles.title}>// TERMS OF SERVICE</Text>
          <Text style={styles.body}>
            {'DARKO is a product of Nxgen Media LLC.\n\nDARKO is an analytical tool provided "as is" for informational and strategic purposes. Nxgen Media LLC is not liable for interpersonal, personal, or financial outcomes resulting from the use of the scripts or strategies generated by this software. All subscription payments are processed securely via our payment gateway.'}
          </Text>
          <View style={styles.sectionDivider} />
          <Text style={styles.body}>
            {'Terms of Service for DARKO. By using DARKO, a product of Nxgen Media LLC, you agree to our terms of service. DARKO is an analytical tool provided "as is" for informational and strategic purposes. Nxgen Media LLC is not liable for interpersonal, personal, or financial outcomes resulting from the use of the scripts or strategies generated by this software. All subscription payments are processed securely via our payment gateway.'}
          </Text>
        </ScrollView>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: BG,
    alignItems: 'center',
  },
  inner: {
    flex: 1,
    width: '100%' as any,
    maxWidth: 640,
    paddingTop: 60,
    paddingHorizontal: 20,
  },
  header: {
    marginBottom: 8,
  },
  back: {
    fontFamily: MONO,
    fontSize: 10,
    color: TEXT_DIM,
    letterSpacing: 2,
  },
  divider: {
    height: 1,
    backgroundColor: BORDER,
    marginVertical: 20,
  },
  content: {
    paddingBottom: 80,
  },
  sectionDivider: {
    height: 1,
    backgroundColor: BORDER,
    marginVertical: 24,
  },
  title: {
    fontFamily: MONO,
    fontSize: 22,
    fontWeight: '700',
    color: TEXT_PRIMARY,
    letterSpacing: 4,
    marginBottom: 24,
  },
  body: {
    fontFamily: MONO,
    fontSize: 13,
    color: TEXT_DIM,
    lineHeight: 22,
    letterSpacing: 0.3,
  },
});
